generator:
  class: sfDoctrineGenerator
  param:
    model_class:           examenes
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          examenes
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  
      list:    
         display: [ _mesa, idmesaexamen, promedio]
         object_actions: 
          _edit:
          _delete:
          mesa:
            name: mesa
            action: mesasexamenes
            params: idexamen=%%idexamen%%
         actions: []
      filter:  
         display: [promedio]
      form:    ~
      edit:    ~
      new:     ~
