# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:
all:
  nb_results_per_page: 50
  perfil:
    admin:       1
    alumno:      2
    facultad:    3
    profesor:    4
  envio_mail:
    contacto: dsposito@gmail.com
    administracion: dsposito@gmail.com

#  wstest1:
#    nuevaspersonas: http://192.168.2.195:9000/alumnos/nuevaspersonas.php?wsdl


  tiny_mce_simple: 
    width: "550px",
    height: "200px",
    language: "es",
    relative_urls: false,
    convert_urls: false,
    plugins: "preview, paste, advlink, fullscreen",
    theme_advanced_buttons1: "bold, italic, underline, separator, justifyleft, justifycenter, justifyright, justifyfull, separator, outdent, indent, separator, pastetext, pasteword, separator, link, bullist, numlist, separator, undo, redo, selectall, separator, preview, code, fullscreen",
    theme_advanced_buttons2: "",
    theme_advanced_buttons3: "",
    plugin_preview_width: "500",
    plugin_preview_height: "600",
    fullscreen_new_window: true,
    theme_advanced_resize_horizontal: false,
    paste_auto_cleanup_on_paste: true,      
