<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/09/27 21:33:55

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=alcec',
  'username' => 'root',
  'password' => 'root911',
  'name' => 'doctrine',
)),);
