generator:
  class: sfDoctrineGenerator
  param:
    model_class:           personas
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          personasegresadas
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    
        actions: {}
      new:     
        title: "Agregar Nueva Persona Egresada"
        actions:
          _save:
