# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases
all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=192.168.2.172;dbname=bdalumnos
      username: alumnos
      password: alumnos911
