generator:
  class: sfDoctrineGenerator
  param:
    model_class:           alumat
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          alumat
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
         display: [id, _materia, _estado ]
      filter:  
         display: [idestadomateria]
      form:    ~
      edit:    ~
      new:     ~
