# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules 
homepage:
  url:   /
  param: { module: sfGuardAuth, action: signin }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }
              
sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }
    
user_logout:
  url:   /logout
  param: { module: usuario, action: logout }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

sf_guard_user:
  url:   /user
  param: { module: sfGuardUser, action: index }

sf_guard_group:
  url:   /group
  param: { module: sfGuardGroup, action: index }

sf_guard_permission:
  url:   /permission
  param: { module: sfGuardPermission, action: index }

libredeuda:
  url:   /libredeuda
  param: { module: libredeuda, action: index }

alumat:
  url:   /alumat
  param: { module: alumat, action: index }

ingreso:
  url:   /ingreso
  param: { module: ingreso, action: index }

calendarios:
  url:   /calendarios
  param: { module: calendarios, action: index }

reglamentos:
  url:   /reglamentos
  param: { module: reglamentos, action: index }

calendar:
  url:   /calendar
  param: { module: calendar, action: index }


solicitudes:
  url:   /solicitudes
  param: { module: solicitudes, action: index }

reglamentos:
  url:   /reglamentos
  param: { module: reglamentos, action: index }

