# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false
    i18n:  on
    #web_debug:              true
    
dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    enabled_modules:      [default, sfGuardAuth, sfGuardGroup, sfGuardUser, sfGuardPermission , sfGuardForgotPassword]
    csrf_secret:            73f3b2e9dfbaf196e808cccf5a0899d78f80fbb8
    timeout: false

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
    i18n:  on
    default_culture:  es_ES

    login_module:           sfGuardAuth
    login_action:           signin

#  .actions:
#    error_404_module: default
#    error_404_action: error404

    #error_404_module: foo   # To be called when a 404 error is raised
    #error_404_action: bar   # Or when the requested URL doesn't match any route
