# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main_autogestion.css, tabla_autogestion.css, av_autogestion.css, datePicker.css, superfish_autogestion.css, superfish-vertical_autogestion.css, jdMenu.css, ui.jqgrid.css, jquery-ui-1.8.20.custom.css]

  javascripts:    [jquery-1.5.1.min.js, jquery-ui-1.8.13.custom.min.js, date.js, jquery.datePicker.js, jquery.dataTables.js, analytics.js , superfish.js,hoverIntent.js, jquery.validator.js, grid.locale-es.js,jquery.jqGrid.min.js, jquery.jdMenu.js ]

  has_layout:     true
  layout:         layout
