<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/09/27 21:28:47
sfConfig::add(array(
  'app_nb_results_per_page' => 50,
  'app_perfil_admin' => 1,
  'app_perfil_alumno' => 2,
  'app_perfil_facultad' => 3,
  'app_perfil_profesor' => 4,
  'app_envio_mail_contacto' => 'dsposito@gmail.com',
  'app_envio_mail_administracion' => 'dsposito@gmail.com',
  'app_tiny_mce_simple_width' => '550px',
  'app_tiny_mce_simple_height' => '200px',
  'app_tiny_mce_simple_language' => 'es',
  'app_tiny_mce_simple_relative_urls' => 'false,',
  'app_tiny_mce_simple_convert_urls' => 'false,',
  'app_tiny_mce_simple_plugins' => 'preview, paste, advlink, fullscreen',
  'app_tiny_mce_simple_theme_advanced_buttons1' => 'bold, italic, underline, separator, justifyleft, justifycenter, justifyright, justifyfull, separator, outdent, indent, separator, pastetext, pasteword, separator, link, bullist, numlist, separator, undo, redo, selectall, separator, preview, code, fullscreen',
  'app_tiny_mce_simple_theme_advanced_buttons2' => '',
  'app_tiny_mce_simple_theme_advanced_buttons3' => '',
  'app_tiny_mce_simple_plugin_preview_width' => '500',
  'app_tiny_mce_simple_plugin_preview_height' => '600',
  'app_tiny_mce_simple_fullscreen_new_window' => 'true,',
  'app_tiny_mce_simple_theme_advanced_resize_horizontal' => 'false,',
  'app_tiny_mce_simple_paste_auto_cleanup_on_paste' => 'true,',
));
