generator:
  class: sfDoctrineGenerator
  param:
    model_class:           EstadosPlanes
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          estados_planes
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:   
        title: "Listado de Estados de Plan de Estudio"
        display: [nombre]
        batch_actions: {}         
        sort: [nombre, asc]
      filter:
        display: [nombre]
      form:    ~
      edit:
        title: "Editar Estado de Plan de Estudio" 
      new:
        title: "Nuevo Estado de Plan de Estudio" 
