alumat:
  class: sfDoctrineRouteCollection
  options:
    model:                alumat
    module:               alumat
    prefix_path:          /alumat
    column:               id
    with_wildcard_routes: true

examenes:
  class: sfDoctrineRouteCollection
  options:
    model:                examenes
    module:               examenes
    prefix_path:          /examenes
    column:               idexamen
    with_wildcard_routes: true

mesasexamenes:
  class: sfDoctrineRouteCollection
  options:
    model:                mesasexamenes
    module:               mesasexamenes
    prefix_path:          /mesasexamenes
    column:               idmesaexamen
    with_wildcard_routes: true

ficha_carga:
  class: sfDoctrineRouteCollection
  options:
    model:                FichaCarga
    module:               ficha_carga
    prefix_path:          /ficha_carga
    column:               idficha
    with_wildcard_routes: true

planesestudios:
  class: sfDoctrineRouteCollection
  options:
    model:                planesestudios
    module:               planesestudios
    prefix_path:          /planesestudios
    column:               idplanestudio
    with_wildcard_routes: true

fichaalumnos:
  class: sfDoctrineRouteCollection
  options:
    model:                fichaalumnos
    module:               fichaalumnos
    prefix_path:          /fichaalumnos
    column:               idmateriaplan
    with_wildcard_routes: true

alumnos:
  class: sfDoctrineRouteCollection
  options:
    model:                alumnos
    module:               alumnos
    prefix_path:          /alumnos
    column:               idalumno
    with_wildcard_routes: true

personas:
  class: sfDoctrineRouteCollection
  options:
    model:                personas
    module:               personas
    prefix_path:          /personas
    column:               idpersona
    with_wildcard_routes: true

# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: default, action: index }




# default rules 
homepage:
  url:   /
  # param: { module: ingreso, action: index }
  param: { module: sfGuardAuth, action: signin }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }
        
sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }
        
sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }
  

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*

sf_guard_user:
  url:   /user
  param: { module: sfGuardUser, action: index }

sf_guard_group:
  url:   /group
  param: { module: sfGuardGroup, action: index }

sf_guard_permission:
  url:   /permission
  param: { module: sfGuardPermission, action: index }

libredeuda:
  url:   /libredeuda
  param: { module: libredeuda, action: index }
